server:
  port: 8083

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secretkey: GALAXY1456KEYROCKSSUPERMARIO123KEYS789HELPSALOTGALAXY1456KEYROCKSSUPERMARIO123KEYS789HELPSALOT

dgs:
  graphql:
    schema-locations:
      - classpath*:**/catalog-schema.graphql*


