///*
// * This file was generated by the Gradle "init" task.
// *
// * This generated file contains a sample Kotlin library project to get you started.
// * For more details take a look at the "Building Java & JVM projects" chapter in the Gradle
// * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
// */
//
plugins {

    kotlin("jvm")
    kotlin("plugin.spring")

    id("org.springframework.boot")
    id("io.spring.dependency-management")

    id("com.netflix.dgs.codegen")
}

group = "com.galaxy"
version = "0.0.1"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
}
dependencies {

    api(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release"))
    api("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter")
    api("com.netflix.graphql.dgs:graphql-dgs-spring-boot-micrometer")

    api("com.graphql-java:graphql-java-extended-scalars:1.0")
    api("com.github.javafaker:javafaker:1.+")

    //For security
    api("org.springframework.boot:spring-boot-starter-security")
    api("io.jsonwebtoken:jjwt-api:0.11.2")
    api("io.jsonwebtoken:jjwt-impl:0.11.2")
    api("io.jsonwebtoken:jjwt-jackson:0.11.2")

    //For logging to json format
    api("org.apache.logging.log4j:log4j-api")
    api("org.apache.logging.log4j:log4j-core")
    api("com.fasterxml.jackson.core:jackson-core")
    api("com.fasterxml.jackson.core:jackson-databind")
    api("com.fasterxml.jackson.core:jackson-annotations")
    api("org.projectlombok:lombok:1.18.20")
    api("com.google.code.gson:gson:2.8.6")

    api("org.springframework.boot:spring-boot-starter-web")
    api("org.springframework.boot:spring-boot-starter-actuator")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}
tasks.bootJar{
    enabled = false
}
tasks.jar{
    enabled = true
}
tasks.generateJava{
    enabled = false
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "11"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}
